objects/S3_Archive_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings for S3 archive</description>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API_Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value of field</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>S3 Archive Settings</label>
</CustomObject>

objects/Task_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>File_name__c</fullName>
        <label>File name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Bucket__c</fullName>
        <label>S3_Bucket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Archived Attachments</label>
    <nameField>
        <label>Task Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archived Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_S3CreateUrl.cls
@isTest
public class Test_S3CreateUrl{   
    static testMethod void verify_class(){
    
    list<S3_Archive_Settings__c > Archivelist = new list<S3_Archive_Settings__c >();
    Task_Attachment__c  taskassign = new Task_Attachment__c(File_name__c='fgh',S3_Bucket__c='68547'); 
    insert taskassign ;
    S3_Archive_Settings__c Archeive=new S3_Archive_Settings__c(Name='S31',API_Key__c='s3_public_key',Value__c ='djfjgj');
    Archivelist.add(Archeive);
   // insert Archeive;
    
    S3_Archive_Settings__c NewArcheive=new S3_Archive_Settings__c(Name='S32',API_Key__c='s3_secret_key',Value__c ='fjgj');
    Archivelist.add(NewArcheive);
    insert Archivelist;
    
    
    // Task_Attachment__c attachment = [select File_name__c,S3_Bucket__c from Task_Attachment__c where Id = :pageId];
  //  S3CreateUrl controller = new S3CreateUrl();
    //string pageId;
   S3CreateUrl.createSignedGetUrl(taskassign.id);

    
      }
    }